services:
  pgvector:
    image: 'pgvector/pgvector:pg16'
    environment:
      - 'POSTGRES_DB=cv-store'
      - 'POSTGRES_PASSWORD=sexcigarez2'
      - 'POSTGRES_USER=thejoker'
    labels:
      - "org.springframework.boot.service-connection=postgres"
    ports:
      - '5432:5432'
